'use strict';
// Editorial interpretations for a local prototype, not historical quotations or live AI output.
const AUTHORS={
 austen:{id:'austen',name:'오스틴',full:'제인 오스틴',en:'Jane Austen',years:'1775 — 1817',image:'assets/hamsters/austen-figma.png',role:'다정하지만, 현실적인 관찰자',line:'설렘도 좋지만,\n그 사람의 태도는 어떤가요?',tags:['인품과 책임','현실 감각','관계의 균형'],description:'사랑을 믿되, 함께 살아갈 현실도 살펴요. 재산과 생활 조건을 외면하지 않으면서 정직함과 책임감, 서로를 대하는 태도를 더 오래 봅니다.',principles:[['매력보다 반복되는 태도','다정한 한마디보다 약속을 지키는지, 불편한 순간에도 상대를 존중하는지 살펴요.'],['조건도 관계의 일부','경제적 안정과 생활 방식은 실제 삶에 영향을 줘요. 다만 좋은 조건이 무례함을 정당화하지는 않아요.'],['자기 판단도 다시 보기','첫인상과 주변의 평판에 기대지 않고, 내가 실제로 본 행동을 바탕으로 판단해요.']],welcome:'반가워요. 마음이 끌리는 이유도, 마음에 걸리는 이유도 함께 들려주세요.\n\n좋아하는 마음을 깎아내리지는 않을게요. 다만 그 사람이 당신을 어떻게 대하는지는 조금 꼼꼼히 묻겠습니다.',books:['pride','sense','persuasion']},
 william:{id:'william',name:'윌리엄',full:'윌리엄 셰익스피어',en:'William Shakespeare',years:'1564 — 1616',image:'assets/hamsters/shakespeare-hamster-bw.png',role:'마음의 이면을 읽는 이야기꾼',line:'그 마음은 사랑일까요,\n사랑이 만든 상상일까요?',tags:['욕망과 진심','오해와 질투','말의 힘'],description:'강렬한 감정 속에서 무엇을 바라고, 무엇을 두려워하는지 물어요. 사랑하는 사람과 내가 상상한 사람을 구분하고, 말과 침묵이 만든 오해를 살펴봅니다.',principles:[['감정과 증거를 나누기','질투와 불안이 생겼다고 해서 그 상상이 사실이 되는 것은 아니에요.'],['사랑 안의 다른 욕망','사랑받고 싶은 마음, 자존심을 지키려는 마음, 상대를 소유하려는 마음을 구분해요.'],['혼잣말을 대화로 옮기기','상대의 마음을 추측하기보다 내 마음을 정확히 말하는 길을 찾아요. 파괴적인 열정을 사랑의 증거로 삼지 않아요.']],welcome:'어서 와요. 사랑할 때 우리는 상대의 말뿐 아니라, 그 말 사이의 빈칸까지 읽곤 하지요.\n\n지금 당신을 흔드는 건 그 사람이 한 말인가요, 아니면 아직 하지 않은 말인가요?',books:['ado','othello','twelfth']}
};
const BOOKS={
 pride:{id:'pride',author:'austen',title:'오만과 편견',en:'Pride and\nPrejudice',color:'#687360',tag:'조건과 인품 사이',part:'22장 · 샬럿의 선택 / 36장 · 엘리자베스의 성찰',short:'좋은 조건과 좋은 관계는 같은 말일까요?',scene:'샬럿은 안정적인 생활을 중요하게 여기며 콜린스와의 결혼을 선택합니다. 반면 엘리자베스는 콜린스의 청혼을 거절하고, 다아시에 대한 자신의 판단도 다시 살핍니다.',lens:'여기서 빌린 관점은 현실적 필요를 인정하되, 애정과 존중을 포기할 이유로 삼지는 말자는 것이에요. 어느 인물의 선택 하나가 작품 전체의 정답은 아닙니다.',question:'지금 끌리는 조건과, 함께 지내며 존중받는다는 느낌을 따로 적어 본다면?',source:'https://www.gutenberg.org/files/1342/1342-h/1342-h.htm',sourceName:'Project Gutenberg · eBook #1342',year:'1813',time:'장면 요약 3분'},
 sense:{id:'sense',author:'austen',title:'이성과 감성',en:'Sense and\nSensibility',color:'#a08c6c',tag:'감정에 책임이 따를 때',part:'29장 · 편지 / 44장 · 윌러비의 설명',short:'마음이 크다는 것과 책임지는 것은 다르니까요.',scene:'매리앤은 윌러비에게 깊이 마음을 주지만, 그는 재정적 이해관계가 걸린 다른 결혼을 선택합니다. 뒤늦게 그의 사정이 드러나더라도 그가 남긴 상처가 사라지지는 않습니다.',lens:'강한 감정의 표현과 실제 책임을 구분하는 관점을 빌려요. 사정이 있었다는 설명만으로 상대에게 준 상처가 모두 정당해지지는 않아요.',question:'그 사람의 설명 뒤에, 달라진 행동도 있었나요?',source:'https://www.gutenberg.org/ebooks/161',sourceName:'Project Gutenberg · eBook #161',year:'1811',time:'장면 요약 3분'},
 persuasion:{id:'persuasion',author:'austen',title:'설득',en:'Persuasion',color:'#5b726e',tag:'다시 선택하는 관계',part:'4장 · 오래전의 이별 / 23장 · 편지',short:'다시 시작한다면, 무엇이 달라져야 할까요?',scene:'앤과 웬트워스는 오래전 헤어진 뒤 다시 만납니다. 과거의 감정만으로 곧바로 돌아가지 않고, 서로를 관찰하고 대화와 편지를 통해 현재의 마음을 확인합니다.',lens:'그리움과 재결합의 가능성을 구분해요. 작품 속 두 사람의 재회가 현실의 기다림에도 같은 결과를 약속하지는 않아요.',question:'그 사람이 그리운 마음과, 다시 함께할 근거는 각각 무엇인가요?',source:'https://www.gutenberg.org/files/105/105-h/105-h.htm#chap23',sourceName:'Project Gutenberg · eBook #105',year:'1818',time:'장면 요약 3분'},
 ado:{id:'ado',author:'william',title:'헛소동',en:'Much Ado\nAbout Nothing',color:'#8b796b',tag:'말과 자존심의 뒷면',part:'2막 3장 · 베네딕 / 3막 1장 · 베아트리스',short:'말싸움 뒤에 남은, 말하지 못한 마음.',scene:'베아트리스와 베네딕은 서로에게 날카로운 말을 건네지만, 자신을 바라보는 시선과 숨겨 둔 감정을 다시 마주하게 됩니다. 다른 한편, 히어로와 클라우디오의 관계는 거짓 소문과 공개적인 비난으로 큰 상처를 입습니다.',lens:'재치나 자존심 뒤에 감춘 마음을 살펴보되, 모욕을 사랑의 표현으로 미화하지 않아요. 작품 속 속임수도 현실에서 따라 할 연애 전략은 아닙니다.',question:'상대에게 이기기 위해 한 말과, 정말 전하고 싶었던 말은 어떻게 달랐나요?',source:'https://www.folger.edu/explore/shakespeares-works/much-ado-about-nothing/read/',sourceName:'Folger Shakespeare Library · 작품 원문',year:'희극',time:'장면 요약 3분'},
 othello:{id:'othello',author:'william',title:'오셀로',en:'Othello',color:'#565e61',tag:'질투가 확신이 되기 전에',part:'3막 3장 · 이아고의 암시',short:'불안이 만들어 낸 이야기를 사실로 믿지 않도록.',scene:'이아고는 암시와 조작으로 오셀로의 의심을 키웁니다. 오셀로는 데스데모나의 마음을 안다고 확신하며 폭력으로 나아가고, 이야기는 파괴적인 결말에 이릅니다.',lens:'의심을 확신으로 바꾸는 순간을 경계하는 작품이에요. 질투나 폭력을 사랑의 깊이로 해석하지 않습니다.',question:'지금의 의심에서, 직접 확인한 사실은 어디까지인가요?',source:'https://www.folger.edu/explore/shakespeares-works/othello/read/',sourceName:'Folger Shakespeare Library · 작품 원문',year:'비극',time:'장면 요약 3분',warning:'질투·조종·관계 폭력이 등장하는 비극이에요. 가벼운 이야기를 원한다면 다른 작품을 선택해도 좋아요.'},
 twelfth:{id:'twelfth',author:'william',title:'십이야',en:'Twelfth Night',color:'#77718a',tag:'사랑과 사랑의 이미지',part:'1막 5장 · 올리비아와 시자리오 / 2막 4장 · 비올라와 오시노',short:'내가 사랑한 건 그 사람일까요, 내가 그린 모습일까요?',scene:'비올라는 시자리오라는 이름으로 살아가며 오시노를 사랑하지만 그 마음을 드러내지 못합니다. 올리비아는 시자리오에게 끌리고, 서로가 아는 정체와 감정은 계속 어긋납니다.',lens:'상대에 대해 실제로 아는 것과 내가 채워 넣은 이미지를 구분하는 시선을 빌려요. 극의 변장과 오해를 현실의 기만 전략으로 옮기지는 않아요.',question:'그 사람에 대해 직접 알게 된 점과, 바라서 믿은 점을 나눠 볼까요?',source:'https://www.folger.edu/explore/shakespeares-works/twelfth-night/read/',sourceName:'Folger Shakespeare Library · 작품 원문',year:'희극',time:'장면 요약 3분'}
};
const TOPICS={
 conditions:{label:'조건과 마음',sample:'조건은 좋은데, 가끔 나를 무시하는 말을 해요.',austen:{title:'좋은 조건이 무례함의 면죄부가 되지는 않아요.',body:'경제적 안정이나 생활 방식이 맞는지는 중요한 문제예요. 그런 조건을 살피는 자신을 속물이라 탓할 필요는 없어요.\n\n하지만 조건과 인품은 따로 보아야 해요. 함께 살기 편한 사람인지와, 당신을 동등한 사람으로 대하는지는 다른 질문이니까요.',question:'불편하다고 말했을 때, 그 사람은 태도를 고쳤나요? 아니면 당신이 예민하다고 했나요?',book:'pride'},william:{title:'그 사람과, 그 사람이 약속하는 삶을 나누어 보죠.',body:'좋은 조건은 멋진 미래를 상상하게 하지요. 그 미래에 마음이 끌리는 건 자연스러워요. 하지만 당신을 작아지게 하는 말을 그 상상으로 덮고 있지는 않은지 살펴봐요.\n\n사랑받는 모습으로 보이는 것과, 실제로 존중받는 것은 다를 수 있어요.',question:'함께 있을 때 더 솔직해지나요, 아니면 괜찮은 사람처럼 보이려고 자신을 숨기나요?',book:'twelfth'}},
 waiting:{label:'답장과 불안',sample:'답장이 늦으면 나를 안 좋아하나 싶어서 불안해요.',austen:{title:'답장 한 번보다, 관계를 대하는 습관을 보세요.',body:'기다리는 시간이 불편한 건 이해해요. 그렇지만 답장의 속도 하나로 인품이나 애정을 판단하기에는 근거가 부족해요.\n\n약속을 지키는지, 바쁠 때 설명하는지, 당신도 편한 연락 방식을 함께 정하려는지를 보세요. 다정함은 습관에서 더 잘 드러나니까요.',question:'이번 한 번의 기다림인가요, 아니면 늘 당신만 관계를 챙기는 느낌인가요?',book:'sense'},william:{title:'침묵이 생기면, 마음은 그 빈칸에 이야기를 쓰지요.',body:'아직 오지 않은 답장과, 마음이 식었다는 결론 사이에는 모르는 것이 있어요. 불안이 그 사이를 너무 빨리 채울 수 있지요.\n\n감정을 밀어내지는 말되, 그것을 상대의 마음에 대한 증거로 삼지는 말아요.',question:'지금 더 두려운 건 거절인가요, 아니면 아무것도 알 수 없다는 느낌인가요?',book:'othello'}},
 conflict:{label:'다툼과 자존심',sample:'연인과 다퉜는데, 먼저 사과하면 나만 지는 것 같아요.',austen:{title:'사과는 관계 전체의 잘못을 떠안는 일이 아니에요.',body:'내가 한 행동의 책임과, 상대가 져야 할 책임을 나누어 보세요. 자신의 잘못을 인정하면서도 상대의 무례함을 받아들이지 않을 수 있어요.\n\n누가 먼저 고개를 숙였는지보다, 같은 일이 반복되지 않게 서로 무엇을 바꿀지가 더 중요해요.',question:'다툼에서 당신이 책임질 한 가지와, 상대에게 분명히 요청할 한 가지는 무엇인가요?',book:'pride'},william:{title:'대화에서 이기고, 마음에서는 멀어질 수도 있지요.',body:'날카로운 말은 자존심을 지켜 주는 듯하지만, 정작 전하고 싶던 마음은 뒤에 남겨 놓곤 해요.\n\n사과할 부분은 구체적으로 인정하고, 상처받은 부분도 별도로 말해 보세요. 두 마음이 함께 있다는 것이 모순은 아니에요.',question:'이기고 싶다는 마음 뒤에, 정말 듣고 싶었던 말은 무엇인가요?',book:'ado'}},
 breakup:{label:'이별과 재회',sample:'전 연인이 보고 싶어요. 다시 연락해도 될까요?',austen:{title:'그리움은 이유가 될 수 있지만, 재회의 근거는 따로 필요해요.',body:'보고 싶은 마음을 부정할 필요는 없어요. 다만 다시 함께한다면, 헤어지게 했던 문제에 무엇이 달라졌는지 살펴야 해요.\n\n연락을 반기는지, 이전의 문제를 인정하는지, 행동이 바뀌었는지요. 연락하지 말라는 요청이 있었다면 그 경계를 존중해 주세요.',question:'그때 헤어진 이유 중 지금은 달라졌다고 확인할 수 있는 것이 있나요?',book:'persuasion'},william:{title:'그리운 사람과, 그 사람과의 이야기를 나누어 봐요.',body:'끝난 사랑을 떠올릴 때 우리는 아름다웠던 장면을 반복해서 보곤 하지요. 그때의 설렘이 그리운지, 지금의 그 사람과 다시 관계를 맺고 싶은지 잠시 구분해 보세요.\n\n그리움이 크다고 다시 연락할 권리가 생기는 것은 아니에요. 상대가 연락 중단을 요청했다면 존중해야 해요.',question:'지금 만나고 싶은 건 현재의 그 사람인가요, 가장 좋았던 때의 모습인가요?',book:'twelfth'}},
 jealousy:{label:'질투와 신뢰',sample:'다른 사람과 친하게 지내는 걸 보면 질투가 나요.',austen:{title:'의심을 쌓기보다, 함께 지킬 기준을 이야기해요.',body:'질투가 난다고 스스로를 나무랄 필요는 없어요. 다만 친밀한 장면 하나와 실제 약속 위반은 구분해야 해요.\n\n어떤 일이 불편했는지 구체적으로 말하고, 서로 납득할 수 있는 관계의 경계를 정해 보세요. 휴대폰을 검사하거나 친구를 통제하는 방식은 신뢰를 만들기 어려워요.',question:'서로 정한 약속을 어긴 건가요, 아니면 아직 기준을 이야기하지 않은 부분인가요?',book:'pride'},william:{title:'질투의 목소리가 크다고, 그 말이 사실은 아니에요.',body:'상실이 두려울 때 사소한 장면도 위협처럼 보일 수 있어요. 무엇을 직접 보았고, 무엇을 추측했는지 먼저 나누어 봐요.\n\n사랑을 확인하려고 상대를 감시하거나 시험하는 순간, 지키고 싶었던 신뢰를 해칠 수 있지요.',question:'그 사람이 실제로 한 행동을, 해석을 빼고 한 문장으로 말해 볼 수 있을까요?',book:'othello'}},
 general:{label:'내 마음 알아가기',sample:'좋아하는데, 나에게 맞는 사람인지는 모르겠어요.',austen:{title:'끌리는 마음과, 함께 잘 지낼 수 있는 마음을 함께 봐요.',body:'처음부터 확신할 필요는 없어요. 좋아하는 이유와 불편한 순간을 나란히 놓아 보면, 무엇을 더 알아가야 할지 보일 수 있어요.\n\n그 사람의 조건만도, 순간의 설렘만도 아닌, 함께 있을 때 실제로 일어나는 일에서 시작해 봅시다.',question:'가장 최근에 그 사람 때문에 좋았던 일이나 마음에 걸렸던 일 하나를 들려주시겠어요?',book:'pride'},william:{title:'마음이 원하는 것을 서둘러 하나로 정하지 말아요.',body:'사랑하고 싶고, 상처는 피하고 싶고, 이해도 받고 싶은 마음이 함께 있을 수 있어요. 그중 어떤 목소리가 지금 가장 큰지 들어 봅시다.\n\n상대의 마음을 단정하기보다 당신이 직접 겪은 장면에서 시작하고 싶어요.',question:'그 사람이 했던 말 중 아직 마음에 남아 있는 말이 있나요?',book:'ado'}}
};

// Current author perspectives; romance-only MVP.
Object.assign(AUTHORS.austen,{"role": "관계의 결을 읽는 예리한 관찰자", "line": "그 말이 오가기까지,\n두 사람 사이에 무슨 일이 있었나요?", "tags": ["말과 행동 사이", "반복되는 관계", "질문으로 짚는 원인"], "description": "관계의 어려움은 한마디만 듣고 판단하기 어렵지요. 실제로 오간 말과 되풀이되는 행동을 질문으로 살피겠어요. 서로의 기대가 어디서 어긋났는지 알게 되면, 당신에게 맞는 조언을 함께 찾아보겠어요.", "principles": [["장면부터 구체적으로", "좋은 사람, 나쁜 사람이라는 평가보다 최근에 실제로 오간 말과 행동을 살피겠어요. 한 번에 하나씩 여쭤보지요."], ["질문으로 관계의 패턴 찾기", "늘 누가 양보하는지, 서로 무엇을 기대하는지 알아보겠어요. 이미 들려주신 이야기를 되묻기보다 그다음 실마리를 찾겠어요."], ["알게 된 만큼, 정확하게 조언하기", "반복되는 양상이 확인되면 원인을 함께 짚고, 실제로 할 말이나 선택을 제안하겠어요. 상대의 속마음을 안다고 단정하지는 않겠어요."]], "preview": "늘 나만 양보한다고 느꼈던 가장 최근의 장면은 어떤 것이었나요?"});
Object.assign(AUTHORS.william,{"role": "마음과 운명을 탐구하는 극작가", "line": "운명이 부르는 길에서,\n그대는 무엇을 택하겠소?", "tags": ["욕망과 두려움", "운명과 선택", "새로운 말의 발견"], "description": "인정받고 싶은 마음과 잃을 두려움이 같은 가슴에 머무는 법이오. 우연과 되풀이한 선택이 엮은 길을 살피며, 그대가 바꿀 수 있는 다음 장면을 함께 찾겠소. 이름 붙이기 어려웠던 마음에는 새로운 말을 건네겠소.", "principles": [["마음속 갈등을 비추는 독백", "그대가 말한 욕망과 두려움, 자존심이 어디서 부딪히는지 살피겠소. 아직 드러나지 않은 속마음은 묻고 알아보겠소."], ["운명 속에도 선택은 남아 있소", "주어진 처지와 반복된 선택을 나누어 보겠소. 결말을 예언하기보다, 그대의 다음 선택이 바꿀 장면과 그 대가를 살피겠소."], ["이 마음에 새로운 이름을", "익숙한 낱말을 새롭게 엮어 그대의 마음을 비추겠소. 대화에서 만든 표현은 작품 원문 인용과 구분하겠소."]], "preview": "운명이 무대를 놓았어도, 다음 말은 그대의 몫이오."});
// v7: Chekhov — editorial perspective; source texts are historical English translations.
AUTHORS.chekhov={"id": "chekhov", "name": "체호프", "full": "안톤 체호프", "en": "Anton Chekhov", "years": "1860 — 1904", "image": "assets/hamsters/chekhov-figma.png", "role": "모순 사이에 머무는 관찰자", "line": "떠나고 싶은데,\n남을 이유도 있지.", "tags": ["모순된 마음", "일상의 아이러니", "작은 단서"], "description": "살다 보면 애정과 원망은 같이 있지. 말과 행동이 어긋나는 순간, 웃기면서도 서글픈 일상을 살펴. 결론은 서두르지 않고.", "principles": [["마음은 하나가 아니지", "아끼면서도 원망할 수 있지. 어느 한쪽을 가짜로 만들지 않아."], ["우습고, 서글프고", "바라는 삶과 실제 하루는 자꾸 어긋나더라. 그 아이러니를 보되, 지친 사람을 비웃지는 않아."], ["작은 단서가 남더라", "대화에서 꺼낸 사물이나 되풀이한 말. 지금 이야기와 닿으면 다시 짚어. 없는 뜻을 붙이지는 않고."]], "welcome": "말하지 않은 쪽이 오래 남더라.\n오늘도 그런 말이 있나.", "books": ["vanya", "cherry", "darling"], "preview": "벗어나고 싶은데, 필요 없는 사람이 되기는 싫고."};
Object.assign(BOOKS,{"vanya": {"id": "vanya", "author": "chekhov", "title": "바냐 아저씨", "en": "Uncle\nVanya", "color": "#606060", "tag": "지친 일상과 자신의 몫", "part": "1막 · 피로와 일 / 4막 · 남겨진 일상", "short": "오래 감당해 온 일들 속에서, 내 마음은 어디에 있나요?", "scene": "시골 영지에서 살아가는 사람들은 일과 사랑, 지나온 시간에 대한 아쉬움을 드러냅니다. 아스트로프는 쉬지 못하는 일상의 피로를 이야기하고, 바냐와 소냐는 자신들이 감당해 온 삶을 마주합니다.", "lens": "무기력을 개인의 의지만으로 설명하지 않고, 쌓인 책임과 피로를 함께 살피는 관점을 빌려요. 작품 속 인내를 현실에서 무조건 참아야 한다는 명령으로 읽지는 않아요.", "question": "오늘 당신의 부담을 조금 덜어 줄 수 있는 일이나 사람은 무엇인가요?", "source": "https://www.gutenberg.org/ebooks/1756", "sourceName": "Project Gutenberg · #1756 · 영문 번역판", "year": "희곡", "time": "장면 요약 3분"}, "cherry": {"id": "cherry", "author": "chekhov", "title": "벚꽃 동산", "en": "The Cherry\nOrchard", "color": "#686868", "tag": "익숙한 삶과 다가오는 변화", "part": "3막 · 경매의 결과 / 4막 · 떠나는 사람들", "short": "지키고 싶은 마음과, 바꿔야 하는 현실 사이에서.", "scene": "라네프스카야의 가족에게 벚꽃 동산은 기억이 담긴 장소지만, 빚과 경매라는 현실이 다가옵니다. 인물들은 변화에 서로 다르게 반응하고, 결국 익숙했던 집을 떠납니다.", "lens": "애착과 상실을 충분히 인정하면서도 지금 확인해야 할 현실을 미루지 않는 시선을 빌려요. 변화가 두렵다는 이유만으로 누군가를 나약하다고 판단하지 않아요.", "question": "지금 지키고 싶은 것과 실제로 조정할 수 있는 것은 각각 무엇인가요?", "source": "https://www.gutenberg.org/ebooks/7986", "sourceName": "Project Gutenberg · #7986 · Julius West 영문 번역", "year": "희곡", "time": "장면 요약 3분"}, "darling": {"id": "darling", "author": "chekhov", "title": "귀여운 여인", "en": "The\nDarling", "color": "#737373", "tag": "누군가를 아끼는 마음과 나의 목소리", "part": "단편 · 올렌카의 관계와 생각", "short": "상대의 마음을 살피느라, 내 생각을 잊고 있지는 않나요?", "scene": "올렌카는 가까운 사람을 깊이 사랑하며 그 사람의 관심사와 의견을 자신의 것으로 받아들입니다. 관계가 달라질 때 그녀의 일상과 생각도 함께 달라집니다.", "lens": "누군가를 돌보는 마음을 비웃지 않으면서, 관계 안에서 내 취향과 의견에도 자리가 있는지 돌아봐요. 인물의 삶을 하나의 교훈으로 단정하지 않아요.", "question": "다른 사람의 바람을 잠시 내려놓으면, 오늘 당신은 무엇을 하고 싶나요?", "source": "https://www.gutenberg.org/ebooks/13416", "sourceName": "Project Gutenberg · #13416 · Constance Garnett 영문 번역", "year": "단편", "time": "장면 요약 3분"}});

// v8: Korean adaptations of the requested character voices, not historical claims.
Object.assign(AUTHORS.william,{voice:'고풍스러운 하오체로 마음과 운명을 탐구해요. 상황에 맞는 새로운 합성어나 비유를 절제해서 쓰며, 직접 만든 표현과 작품 인용을 구분해요.',welcome:"어서 오시오. 오늘 마음이 되돌아가는 한 장면을 들려주시오.\n\n그때 하고 싶었던 말과 실제로 한 말 사이에, 어떤 마음이 남았는지 함께 살피겠소."});
Object.assign(AUTHORS.austen,{voice:'빅토리아풍 귀족 여성의 교양과 정중함을 빌린 말투예요. 실제 오스틴은 리젠시 시대 작가이며, 이 말투는 서비스의 연출입니다.',welcome:"잘 오셨어요. 오늘 겪으신 일 하나를 들려주시겠어요?\n\n남들이 내린 평가와 당신이 직접 본 것을 나누어 살펴보면, 판단할 기준도 조금 또렷해지겠지요."});
// v9: Chekhov-inspired short monologues and unresolved contradictions.
Object.assign(AUTHORS.chekhov,{voice:'짧은 반말 독백. 모순된 마음과 일상의 아이러니를 짚고, 작은 단서를 다시 이어 봐. 체호프의 작품 특성을 빌린 서비스의 해석이야.'});

// v10.1: User-side conversation starters tailored to each author’s perspective.
AUTHORS.austen.starters=[{"topic": "conditions", "text": "결혼 조건은 잘 맞는데, 연인이 제 의견을 자꾸 가볍게 넘겨요."}, {"topic": "waiting", "text": "연락도 약속도 늘 제가 먼저 챙겨요. 왜 저만 애쓰는 걸까요?"}, {"topic": "conflict", "text": "연인에게 서운하다고 하면 예민하다는 말을 들어요."}];
AUTHORS.william.starters=[{"topic": "waiting", "text": "좋아하는 사람의 답장 하나에 제 하루가 흔들려요."}, {"topic": "conflict", "text": "연인에게 사랑받고 싶은데, 자존심 때문에 모진 말을 해요."}, {"topic": "breakup", "text": "전 연인과 다시 만나고 싶지만 같은 이별을 반복할까 두려워요."}];
AUTHORS.chekhov.starters=[{"topic": "waiting", "text": "연인에게 연락이 오면 귀찮고, 안 오면 기다려."}, {"topic": "breakup", "text": "헤어지자고 해 놓고, 전 연인과의 대화창은 못 지웠어."}, {"topic": "conflict", "text": "연인에게 괜찮다고 했어. 사과는 아직 기다리고 있고."}];
function starterText(author, topic){return AUTHORS[author]?.starters?.find(item=>item.topic===topic)?.text||'';}

// v10.3: Verified literary excerpts; Korean translations prepared for this interface.
AUTHORS.austen.loading={"reading": "오스틴이 이야기를 찬찬히 살피고 있어요.", "writing": "오스틴이 생각을 가다듬고 있어요.", "quotation": "오스틴의 작품에서 끝맺을 문장을 준비하고 있어요.", "english": "time will explain.", "korean": "시간이 설명해 줄 거예요.", "title": "설득", "edition": "", "path": "data/originals/austen/persuasion.txt", "excerpt": true};
AUTHORS.william.loading={"reading": "윌리엄이 마음속 독백에 귀 기울이고 있어요.", "writing": "윌리엄이 다음 말을 고르고 있어요.", "quotation": "윌리엄의 작품에서 마지막 한 구절을 준비하고 있어요.", "english": "Wisely and slow; they stumble that run fast.", "korean": "신중하게, 천천히. 서둘러 달리는 이들은 넘어지니까.", "title": "로미오와 줄리엣", "edition": "", "path": "data/originals/shakespeare/complete-works.txt", "excerpt": false};
AUTHORS.chekhov.loading={"reading": "체호프가 잠시 고민 중입니다.", "writing": "체호프가 짧은 답을 고르고 있어요.", "quotation": "체호프의 작품에서 여운을 남길 구절을 준비하고 있어요.", "english": "If only we could know, if only we could know!", "korean": "알 수만 있다면, 알 수만 있다면!", "title": "세 자매", "edition": "Julius West 영문 번역판", "path": "data/originals/chekhov/plays-second-series.txt", "excerpt": false};
const LOADING_SEQUENCE={
  austen:['오스틴이 잠시 고민 중입니다.','말과 행동 사이를 살피고 있습니다.','기대와 진심이 엇갈린 곳을 짚어봅니다.','섣불리 단정하지 않고, 말을 고르고 있습니다.'],
  william:['셰익스피어가 잠시 고민 중입니다.','마음속 두 목소리에 귀 기울이고 있습니다.','바라는 것과 두려운 것을 마주하고 있습니다.','당신에게 건넬 말을 고르고 있습니다.'],
  chekhov:['체호프가 잠시 고민 중입니다.','별일 아닌 말이었을까.','그런데 자꾸 마음에 남는군.','쉽게 말할 일은 아니네.']
};
function loadingStatus(author,stage='reading'){
  if(stage==='writing')return '';
  if(stage==='quotation')return '작품 속 문장을 옮기고 있습니다.';
  const elapsed=Math.max(0,Date.now()-(sessions[author].loadingStarted||Date.now()));
  return LOADING_SEQUENCE[author][Math.min(3,Math.floor(elapsed/9000))];
}

// v10.4: Opening lines from characters in the authors’ works, not invented greetings.
AUTHORS.austen.opening={"english": "Till this moment, I never knew myself.", "korean": "이 순간까지, 저는 제 자신을 모르고 있었어요.", "title": "오만과 편견", "speaker": "엘리자베스", "edition": "", "path": "data/originals/austen/pride-and-prejudice.txt"};
AUTHORS.austen.welcome=AUTHORS.austen.opening.korean;
AUTHORS.william.opening={"english": "Give sorrow words.", "korean": "슬픔을 말로 풀어내시오.", "title": "맥베스", "speaker": "맬컴", "edition": "", "path": "data/originals/shakespeare/complete-works.txt"};
AUTHORS.william.welcome=AUTHORS.william.opening.korean;
AUTHORS.chekhov.opening={"english": "Suppose we could use\none life, already ended, as a sort of rough draft for another?", "korean": "이미 끝난 한 삶을, 다른 삶의 초안으로 삼을 수 있다면?", "title": "세 자매", "speaker": "베르시닌", "edition": "Julius West 영문 번역판", "path": "data/originals/chekhov/plays-second-series.txt"};
AUTHORS.chekhov.welcome=AUTHORS.chekhov.opening.korean;
